version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:5.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: vi-try
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - vi-try-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:password@mongodb:27017/vi-try?authSource=admin
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-here
    depends_on:
      - mongodb
    networks:
      - vi-try-network
    volumes:
      - .env:/app/.env.local

volumes:
  mongodb_data:

networks:
  vi-try-network:
    driver: bridge